---
name: Validate YAML Files
on:
  workflow_call:
  push:

jobs:
  linter:
    name: Validate Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Lint Yaml Files
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3
        with:
          config_data: |
            extends: default
            rules:
              line-length:
                level: warning
                max: 120
              brackets:
                max-spaces-inside: 1
